import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// ✅ custom font from /app/fonts/f1.ttf
const f1 = localFont({
  src: "./fonts/f1.ttf",
  variable: "--font-f1",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${f1.variable} font-f1 antialiased`}>
        {children}
      </body>
    </html>
  );
}
